[tools]
node = "24.14.1"
"npm:lighthouse" = "latest"
pnpm = "10.33.0"
yarn = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:oxfmt" = "latest"
"npm:resend-cli" = "latest"
"npm:wp-studio" = "latest"
"npm:agent-browser" = "latest"
"npm:playwright" = "latest"
"npm:difit" = "latest"
"npm:@nulab/bee" = "latest"
