[tools]
node = "24.12"
"npm:lighthouse" = "latest"
pnpm = "10.30.2"
yarn = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:diffity" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:oxfmt" = "latest"
"npm:resend-cli" = "latest"
